modLoader="javafml"
loaderVersion="[34,)"
license="All rights reserved"
issueTrackerURL="https://github.com/ChAoSUnItY/EkiLib/issues"
[[mods]]
modId="eki"
version="2.0.0"
displayName="Eki Mod"
updateJSONURL="https://www.curseforge.com/minecraft/mc-mods/eki-mod"
displayURL="https://www.curseforge.com/minecraft/mc-mods/eki-mod"
logoFile="examplemod.png"
credits="Those old texture / model contributors from 1.12.2 eki mod"
authors="ChAoS_UnItY"
description='''
A new generation station decoration mod!
'''
[[dependencies.eki]]
    modId="forge"
    mandatory=true
    versionRange="[34,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.eki]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.3]"
    ordering="NONE"
    side="BOTH"
[[dependencies.eki]]
    modId="eki_lib"
    mandatory=true
    versionRange="[1.0.3]"
    ordering="NONE"
    side="BOTH"
